<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AltTester-Driver" Version="[2.3.3-dcl.transport.1edf7a82]" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <None Include="../../packages/nuget/alttester-provenance.json" Link="alttester-provenance.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../packages/nuget/*.nupkg" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
