global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Threading;
global using NUnit.Framework;
global using Allure.Net.Commons;
global using Allure.NUnit;
global using Allure.NUnit.Attributes;
global using AltTester.AltTesterSDK.Driver;
global using ExplorerAutomation.Tests.Common;
global using ExplorerAutomation.Tests.Common.Snapshots;
global using ExplorerAutomation.Tests.Common.Visual;
global using ExplorerAutomation.Tests.Views.Elements;
global using ExplorerAutomation.Tests.Views;
global using AltTester.AltTesterSDK.Driver.Notifications;
global using By = AltTester.AltTesterSDK.Driver.By;
global using SkiaSharp;
